service: htmlToPdf

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'staging'}
  region: eu-west-1

functions:
  htmlToPdf:
    handler: handler.htmlToPdf
    layers:
      - ${cf:executables-layer-${self:provider.stage}.HtmlToPdfLayerExport}

# serverless optimization
package:
  individually: true

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ../webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk
      packagePath: ../package.json

plugins:
  - serverless-webpack
  - serverless-offline
